package CorbaApp;

/**
* CorbaApp/LamportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Processus.idl
* Sunday, 12 January 2020 15:02:16 o'clock WEST
*/

public final class LamportHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaApp.Lamport value = null;

  public LamportHolder ()
  {
  }

  public LamportHolder (CorbaApp.Lamport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaApp.LamportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaApp.LamportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaApp.LamportHelper.type ();
  }

}
