package CorbaApp;


/**
* CorbaApp/LamportHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Processus.idl
* Sunday, 12 January 2020 15:02:16 o'clock WEST
*/

abstract public class LamportHelper
{
  private static String  _id = "IDL:CorbaApp/Lamport:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaApp.Lamport that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaApp.Lamport extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaApp.LamportHelper.id (), "Lamport");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaApp.Lamport read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LamportStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaApp.Lamport value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaApp.Lamport narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaApp.Lamport)
      return (CorbaApp.Lamport)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaApp._LamportStub stub = new CorbaApp._LamportStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaApp.Lamport unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaApp.Lamport)
      return (CorbaApp.Lamport)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaApp._LamportStub stub = new CorbaApp._LamportStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
